// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tawaka.Infrastructure.Persistence;

#nullable disable

namespace Tawaka.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PayrollDbContext))]
    [Migration("20260912221408_InitialFoundation")]
    partial class InitialFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Tawaka.Domain.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Machine")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("EntityName", "EntityId", "OccurredAt");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Tawaka.Domain.Currencies.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Currencies", (string)null);
                });

            modelBuilder.Entity("Tawaka.Domain.Currencies.ExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("Rate")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("RateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RateType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FromCurrency", "ToCurrency", "RateType", "RateDate")
                        .IsUnique();

                    b.ToTable("ExchangeRates", (string)null);
                });

            modelBuilder.Entity("Tawaka.Domain.Payroll.AppSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("Tawaka.Domain.Payroll.PayrollPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PayDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaxYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PayrollPeriods", (string)null);
                });

            modelBuilder.Entity("Tawaka.Domain.Statutory.StatutoryRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CalculationMethod")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RuleId")
                        .IsUnique();

                    b.HasIndex("VerificationStatus");

                    b.HasIndex("EffectiveFrom", "EffectiveTo");

                    b.ToTable("StatutoryRules", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Tawaka.Domain.Statutory.TaxBracket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("FixedDeduction")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LowerBound")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Rate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TaxRuleId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpperBound")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaxRuleId", "Sequence")
                        .IsUnique();

                    b.ToTable("TaxBrackets", (string)null);
                });

            modelBuilder.Entity("Tawaka.Domain.Statutory.AidsLevyRule", b =>
                {
                    b.HasBaseType("Tawaka.Domain.Statutory.StatutoryRule");

                    b.Property<int>("Base")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Rate")
                        .HasColumnType("INTEGER");

                    b.ToTable("AidsLevyRules", (string)null);
                });

            modelBuilder.Entity("Tawaka.Domain.Statutory.ApwcsRule", b =>
                {
                    b.HasBaseType("Tawaka.Domain.Statutory.StatutoryRule");

                    b.Property<int>("Base")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CeilingAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IndustryClassification")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IndustryCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<long>("Rate")
                        .HasColumnType("INTEGER");

                    b.ToTable("ApwcsRules", (string)null);
                });

            modelBuilder.Entity("Tawaka.Domain.Statutory.CurrencyTaxStrategyRule", b =>
                {
                    b.HasBaseType("Tawaka.Domain.Statutory.StatutoryRule");

                    b.Property<string>("AdvisorReference")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ApprovedByAdvisor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("RateDetermination")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RateType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strategy")
                        .HasColumnType("INTEGER");

                    b.ToTable("CurrencyTaxStrategyRules", (string)null);
                });

            modelBuilder.Entity("Tawaka.Domain.Statutory.EmployerLevyRule", b =>
                {
                    b.HasBaseType("Tawaka.Domain.Statutory.StatutoryRule");

                    b.Property<int>("Base")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DueDayOfFollowingMonth")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EmployeePortionRate")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EmployerPortionRate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LevyType")
                        .HasColumnType("INTEGER");

                    b.ToTable("EmployerLevyRules", (string)null);
                });

            modelBuilder.Entity("Tawaka.Domain.Statutory.NssaEligibilityRule", b =>
                {
                    b.HasBaseType("Tawaka.Domain.Statutory.StatutoryRule");

                    b.Property<string>("Condition")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmploymentTypeCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("INTEGER");

                    b.ToTable("NssaEligibilityRules", (string)null);
                });

            modelBuilder.Entity("Tawaka.Domain.Statutory.NssaRule", b =>
                {
                    b.HasBaseType("Tawaka.Domain.Statutory.StatutoryRule");

                    b.Property<long>("CeilingAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CeilingApplication")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CeilingPeriodBasis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EarningsBasis")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EmployeeRate")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EmployerRate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GrossUpEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("GrossUpTriggerMultiplier")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaximumAge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumAge")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinimumDaysInMonth")
                        .HasColumnType("INTEGER");

                    b.ToTable("NssaRules", (string)null);
                });

            modelBuilder.Entity("Tawaka.Domain.Statutory.TaxCreditRule", b =>
                {
                    b.HasBaseType("Tawaka.Domain.Statutory.StatutoryRule");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountPeriodBasis")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AnnualCap")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreditType")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PercentageOfQualifyingAmount")
                        .HasColumnType("INTEGER");

                    b.ToTable("TaxCreditRules", (string)null);
                });

            modelBuilder.Entity("Tawaka.Domain.Statutory.TaxExemptionRule", b =>
                {
                    b.HasBaseType("Tawaka.Domain.Statutory.StatutoryRule");

                    b.Property<int>("ExemptionType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LimitAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LimitPeriodBasis")
                        .HasColumnType("INTEGER");

                    b.ToTable("TaxExemptionRules", (string)null);
                });

            modelBuilder.Entity("Tawaka.Domain.Statutory.TaxRule", b =>
                {
                    b.HasBaseType("Tawaka.Domain.Statutory.StatutoryRule");

                    b.Property<int>("PeriodBasis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaxYear")
                        .HasColumnType("INTEGER");

                    b.ToTable("TaxRules", (string)null);
                });

            modelBuilder.Entity("Tawaka.Domain.Statutory.StatutoryRule", b =>
                {
                    b.OwnsOne("Tawaka.Domain.Statutory.RuleSource", "Source", b1 =>
                        {
                            b1.Property<Guid>("StatutoryRuleId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("TEXT")
                                .HasColumnName("Source");

                            b1.Property<DateOnly?>("SourceDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("SourceDate");

                            b1.Property<string>("SourceReference")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("SourceReference");

                            b1.Property<DateTimeOffset?>("VerifiedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("VerifiedAt");

                            b1.Property<string>("VerifiedBy")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("VerifiedBy");

                            b1.HasKey("StatutoryRuleId");

                            b1.ToTable("StatutoryRules");

                            b1.WithOwner()
                                .HasForeignKey("StatutoryRuleId");
                        });

                    b.Navigation("Source")
                        .IsRequired();
                });

            modelBuilder.Entity("Tawaka.Domain.Statutory.TaxBracket", b =>
                {
                    b.HasOne("Tawaka.Domain.Statutory.TaxRule", "TaxRule")
                        .WithMany("Brackets")
                        .HasForeignKey("TaxRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaxRule");
                });

            modelBuilder.Entity("Tawaka.Domain.Statutory.AidsLevyRule", b =>
                {
                    b.HasOne("Tawaka.Domain.Statutory.StatutoryRule", null)
                        .WithOne()
                        .HasForeignKey("Tawaka.Domain.Statutory.AidsLevyRule", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tawaka.Domain.Statutory.ApwcsRule", b =>
                {
                    b.HasOne("Tawaka.Domain.Statutory.StatutoryRule", null)
                        .WithOne()
                        .HasForeignKey("Tawaka.Domain.Statutory.ApwcsRule", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tawaka.Domain.Statutory.CurrencyTaxStrategyRule", b =>
                {
                    b.HasOne("Tawaka.Domain.Statutory.StatutoryRule", null)
                        .WithOne()
                        .HasForeignKey("Tawaka.Domain.Statutory.CurrencyTaxStrategyRule", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tawaka.Domain.Statutory.EmployerLevyRule", b =>
                {
                    b.HasOne("Tawaka.Domain.Statutory.StatutoryRule", null)
                        .WithOne()
                        .HasForeignKey("Tawaka.Domain.Statutory.EmployerLevyRule", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tawaka.Domain.Statutory.NssaEligibilityRule", b =>
                {
                    b.HasOne("Tawaka.Domain.Statutory.StatutoryRule", null)
                        .WithOne()
                        .HasForeignKey("Tawaka.Domain.Statutory.NssaEligibilityRule", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tawaka.Domain.Statutory.NssaRule", b =>
                {
                    b.HasOne("Tawaka.Domain.Statutory.StatutoryRule", null)
                        .WithOne()
                        .HasForeignKey("Tawaka.Domain.Statutory.NssaRule", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tawaka.Domain.Statutory.TaxCreditRule", b =>
                {
                    b.HasOne("Tawaka.Domain.Statutory.StatutoryRule", null)
                        .WithOne()
                        .HasForeignKey("Tawaka.Domain.Statutory.TaxCreditRule", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tawaka.Domain.Statutory.TaxExemptionRule", b =>
                {
                    b.HasOne("Tawaka.Domain.Statutory.StatutoryRule", null)
                        .WithOne()
                        .HasForeignKey("Tawaka.Domain.Statutory.TaxExemptionRule", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tawaka.Domain.Statutory.TaxRule", b =>
                {
                    b.HasOne("Tawaka.Domain.Statutory.StatutoryRule", null)
                        .WithOne()
                        .HasForeignKey("Tawaka.Domain.Statutory.TaxRule", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tawaka.Domain.Statutory.TaxRule", b =>
                {
                    b.Navigation("Brackets");
                });
#pragma warning restore 612, 618
        }
    }
}
